# [START cloudbuild]
steps:
# This step runs the unit tests on the app
- name: 'python:3.7-slim'
  id: UnitTest
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && pip install pytest &&  pytest unit-test/main_test.py -v'

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/smdata2022/hello-cloudbuild:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/smdata2022/hello-cloudbuild:$SHORT_SHA'


- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/smdata2022/hello-world', '--build-arg=JAR_FILE=target/build-artifact', '.']
images: ['gcr.io/smdata2022/hello-world']

# Building java application using maven 
# - name: maven:3-jdk-9
#   entrypoint: mvn
#   args: ['--version']
# # [END cloudbuild]

# # Package yout app
# - name: maven:3-jdk-8
#   entrypoint: mvn
#   args: ['package','-Dmaven.test.skip=true']

# - name: gcr.io/cloud-builders/docker
#   args: ['build', '-t', 'gcr.io/smdata2022/my-df-java', '--build-arg=JAR_FILE=target/build-artifact', '.']
# images: ['gcr.io/smdata2022/my-df-java']

# Compile and run the packaged java file
# - name: gcr.io/cloud-builders/mvn
#   args:[compile, 
#   exec:java,
#   -Dexec.mainClass=com.examples.pubsub.streaming/PubSubToGcs,
#   "-Dexec.args \
#   --jobName=my-new-job5 \
#   --subnetwork=default\
#   --network=default \
#   --project=smdata2022 \
#   --region=us-central1 \
#   --inputTopic=projects/smdata2022/topics/mytopic \
#   --output=gs://quickstart-dataflow-smdata2022/samples/output \
#   --gcpTempLocation=gs://quickstart-dataflow-smdata2022/temp \
#   --runner=DataflowRunner \
#   --windowSize=2"


#steps:
# This step deploys the new version of our container image
# in the us-central1-bcs-global-comm-fb7c3617-gke Kubernetes Engine cluster.
#- name: 'gcr.io/cloud-builders/kubectl'
#  id: Deploy
#  args:
#  - 'apply'
#  - '-f'
#  - 'kubernetes.yaml'
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
# - 'CLOUDSDK_CONTAINER_CLUSTER=us-central1-bcs-global-comm-fb7c3617-gke'